### ISSUE TITLE
DateTimePickerformfield is old

### ISSUE THREAD

**Issue by steviehines** [PacktPublishing/Flutter-for-Beginners#1]
https://github.com/PacktPublishing/Flutter-for-Beginners/blob/0ea2d1e66246b01da01a2089ade130be3d9bdce1/Chapter08/hands_on_firebase/lib/pages/request_favors_page.dart#L170

Package datetime_picker_formfield: 1.0.0 doesn't work with DateTimePickerformfield

**Comment by ugurcany** [comment]
I guess the library has got updated, `DateTimePickerFormField` became `DateTimeField`. You can check the new usage here: https://pub.dev/packages/datetime_picker_formfield
